[package]
authors     = ["lxl66566 <lxl66566@gmail.com>"]
categories  = ["template-engine", "text-processing"]
description = "A string formatting crate for maps and custom types"
edition     = "2024"
homepage    = "https://github.com/lxl66566/GalgameManager/src-tauri/easy_strfmt"
keywords    = ["string", "format", "template", "strfmt"]
license     = "MIT OR Apache-2.0"
name        = "easy_strfmt"
readme      = "README.md"
repository  = "https://github.com/lxl66566/GalgameManager"
version     = "0.1.0"

[lints.rust]
unsafe_code           = "allow"
unused_qualifications = "warn"

[lints.clippy]
all                     = { level = "warn", priority = -1 }
cargo                   = { level = "warn", priority = -1 }
doc_markdown            = "allow"
missing_errors_doc      = "allow"
missing_panics_doc      = "allow"
multiple_crate_versions = "allow"
pedantic                = { level = "warn", priority = -1 }

[features]
default  = []
indexmap = ["dep:indexmap"]

[dependencies]
indexmap  = { version = "2", optional = true }
thiserror = "2"
