// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThemeMode } from "./ThemeMode";
import type { TimeDisplayConfig } from "./TimeDisplayConfig";

export type AppearanceConfig = {
  theme: ThemeMode;
  language: string;
  timeDisplay: TimeDisplayConfig;
};
