// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Architecture preference for DLL injection.
 *
 * - `Auto`: detect from game executable (default)
 * - `X86`:  force 32-bit DLLs
 * - `X64`:  force 64-bit DLLs
 */
export type ArchPreference = "auto" | "x86" | "x64";
