// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchiveAlgo } from "./ArchiveAlgo";

export type ArchiveConfig = {
  algorithm: ArchiveAlgo;
  level: number;
  backupBeforeRestore: boolean;
};
