// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Global metadata for the AutoUpload plugin (stored in `PluginMetadatas`).
 */
export type AutoUploadPluginMeta = { enabled: boolean; autoAdd: boolean };
