// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoUploadGameConfig } from "./AutoUploadGameConfig";

/**
 * Global metadata for the AutoUpload plugin (stored in `PluginMetadatas`).
 */
export type AutoUploadPluginMeta = {
  enabled: boolean;
  autoAdd: boolean;
  /**
   * Default per-game config applied when the plugin is added to a new game.
   */
  configDefaults: AutoUploadGameConfig;
};
