// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetentionScope } from "./RetentionScope";

/**
 * Per-game config for the AutoUpload plugin.
 */
export type AutoUploadGameConfig = {
  /**
   * Max number of archives to keep for this game; the oldest are evicted
   * (末位淘汰) once exceeded. `0` means unlimited.
   */
  maxKept: number;
  /**
   * Where the retention policy is enforced.
   */
  retentionScope: RetentionScope;
};
