// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginMetadatasPatch } from "./PluginMetadatasPatch";
import type { SettingsPatch } from "./SettingsPatch";

export type ConfigPatch = {
  games?: Array<import("~/utils/patch").GameListOp>;
  devices?: Array<import("~/utils/patch").DeviceListOp>;
  settings: SettingsPatch;
  pluginMetadatas: PluginMetadatasPatch;
};
