// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";
import type { Game } from "./Game";
import type { Settings } from "./Settings";

export type Config = {
  dbVersion: number;
  /**
   * The last time the config was updated from frontend
   */
  lastUpdated: string;
  /**
   * The last time the config was uploaded to remote storage
   */
  lastUploaded: string | null;
  games: Array<Game>;
  devices: Array<Device>;
  settings: Settings;
};
