// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";
import type { DevicePatch } from "./DevicePatch";
import type { Game } from "./Game";
import type { GamePatch } from "./GamePatch";
import type { ListPatchOp } from "./ListPatchOp";
import type { PluginMetadatasPatch } from "./PluginMetadatasPatch";
import type { SettingsPatch } from "./SettingsPatch";

export type ConfigPatch = {
  games: Array<ListPatchOp<Game, GamePatch, number>>;
  devices: Array<ListPatchOp<Device, DevicePatch, string>>;
  settings: SettingsPatch;
  pluginMetadatas: PluginMetadatasPatch;
};
