// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";
import type { Game } from "./Game";

export type Config = {
  dbVersion: number;
  lastUpdated: string;
  games: Array<Game>;
  devices: Array<Device>;
};
