// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutePhase } from "./ExecutePhase";
import type { ExitSignal } from "./ExitSignal";

/**
 * Per-game config for the Execute plugin.
 */
export type ExecuteGameConfig = {
  on: ExecutePhase;
  cmd: string;
  /**
   * When `true`, the cmd must contain a `{}` placeholder which will be
   * replaced with the resolved game executable path.
   */
  passExePath: boolean;
  currentDir: string;
  env: { [key in string]: string };
  /**
   * Signal to send to the spawned process when the game exits.
   */
  exitSignal: ExitSignal;
};
