// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteGameConfig } from "./ExecuteGameConfig";

/**
 * Global metadata for the Execute plugin (stored in `PluginMetadatas`).
 */
export type ExecutePluginMeta = {
  enabled: boolean;
  autoAdd: boolean;
  configDefaults: ExecuteGameConfig;
};
