// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When the execute command should fire.
 */
export type ExecutePhase = "beforeGameStart" | "afterGameStart" | "gameExit";
