// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Signal to send to the spawned process when the game exits.
 */
export type ExitSignal = "none" | "sigterm" | "sigkill";
