// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstance } from "./PluginInstance";

export type Game = {
  id: number;
  name: string;
  excutablePath: string | null;
  savePaths: Array<string>;
  imageUrl: string | null;
  imageSha256: string | null;
  addedTime: string;
  /**
   * [secs, nanos]
   */
  useTime: [number, number];
  lastPlayedTime: string | null;
  lastUploadTime: string | null;
  /**
   * Daily playtime owned by this game: date (YYYY-MM-DD) -> seconds played.
   * Lives on the game (not the Config root) so it migrates, syncs and is
   * cleared together with the rest of the game's state.
   */
  dailyPlaytime?: { [key in string]: number };
  /**
   * Cover-derived accent color (CSS hex, e.g. "#1f80c8") used by the
   * statistics charts. Extracted once via `prepare_image` and cached here
   * so repeat renders are free. Cleared by the frontend whenever the cover
   * URL changes, so a new cover gets a fresh color on its next load.
   */
  coverColor?: string | null;
  plugins?: Array<PluginInstance>;
};
