// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginInstance } from "./PluginInstance";

export type GamePatch = {
  name?: string;
  excutablePath?: string | null;
  savePaths?: Array<string>;
  imageUrl?: string | null;
  imageSha256?: string | null;
  addedTime?: string;
  useTime?: [number, number];
  lastPlayedTime?: string | null;
  lastUploadTime?: string | null;
  dailyPlaytime?: { [key in string]: number };
  coverColor?: string | null;
  plugins?: Array<PluginInstance>;
};
