// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Game = {
  name: string;
  excutablePath: string | null;
  savePaths: Array<string>;
  imageUrl: string | null;
  imageSha256: string | null;
  addedTime: string;
  lastPlayedTime: string | null;
  useTime: [number, number];
};
