// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-game config for the GameWrapper plugin.
 */
export type GameWrapperGameConfig = {
  /**
   * The command to launch instead of the game exe directly.
   * Must contain `{}` which will be replaced with the game exe path.
   */
  cmd: string;
  currentDir: string;
  env: { [key in string]: string };
};
