// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameWrapperGameConfig } from "./GameWrapperGameConfig";

/**
 * Global metadata for the GameWrapper plugin (stored in `PluginMetadatas`).
 */
export type GameWrapperPluginMeta = {
  enabled: boolean;
  autoAdd: boolean;
  configDefaults: GameWrapperGameConfig;
};
