// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LaunchConfig = {
  /**
   * Precise mode for playtime tracking
   */
  precisionMode: boolean;
  /**
   * Enable daily playtime statistics
   */
  dailyStat: boolean;
};
