// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LaunchConfig = {
  /**
   * Precise mode for playtime tracking
   */
  precisionMode: boolean;
  /**
   * Enable daily playtime statistics
   */
  dailyStat: boolean;
  /**
   * Seconds after local midnight at which a statistics day starts
   * (14400 = 04:00: playtime before 04:00 counts toward the previous day).
   * Affects future recordings only; existing keys are not rewritten.
   */
  dayStart: number;
};
