// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single fine-grained operation on a list field.
 *
 * `T` is the element type, `TPatch` is its patch type, and `ID` is the
 * identifier type used to address individual elements.
 *
 * With the `ts` feature, this type also derives `ts_rs::TS`, so patch
 * structs containing list fields can be exported to TypeScript as a
 * generic discriminated union (`{ op: "modify", id: ID, value: TPatch }`
 * etc.). Types referencing `ListPatchOp` are exported alongside it by
 * ts-rs's dependency mechanism; no extra annotation is needed downstream.
 */
export type ListPatchOp<T, TPatch, ID> =
  | { "op": "prepend"; value: T }
  | { "op": "append"; value: T }
  | { "op": "insert"; index: number; value: T }
  | { "op": "modify"; id: ID; value: TPatch }
  | { "op": "delete"; id: ID };
