// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocaleEmulatorGameConfig } from "./LocaleEmulatorGameConfig";

export type LocaleEmulatorPluginMetaPatch = {
  enabled?: boolean;
  autoAdd?: boolean;
  configDefaults?: LocaleEmulatorGameConfig;
};
