// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocaleEmulatorGameConfig } from "./LocaleEmulatorGameConfig";

/**
 * Global metadata for the LocaleEmulator plugin (stored in `PluginMetadatas`).
 */
export type LocaleEmulatorPluginMeta = {
  enabled: boolean;
  autoAdd: boolean;
  configDefaults: LocaleEmulatorGameConfig;
};
