// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-game config for the LocaleEmulator plugin.
 */
export type LocaleEmulatorGameConfig = {
  /**
   * The command to launch the game through Locale Emulator.
   * Must contain `{}` which will be replaced with the game exe path.
   * Default: 'your_path/LEProc.exe "{}"'
   */
  cmd: string;
};
