// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoUploadPluginMeta } from "./AutoUploadPluginMeta";
import type { ExecutePluginMeta } from "./ExecutePluginMeta";
import type { GameWrapperPluginMeta } from "./GameWrapperPluginMeta";
import type { LocaleEmulatorPluginMeta } from "./LocaleEmulatorPluginMeta";
import type { TranslatorPluginMeta } from "./TranslatorPluginMeta";
import type { VoiceSpeedupPluginMeta } from "./VoiceSpeedupPluginMeta";
import type { VoiceZerointerruptPluginMeta } from "./VoiceZerointerruptPluginMeta";
import type { WinePluginMeta } from "./WinePluginMeta";

/**
 * Per-plugin-type metadata, keyed by plugin ID.
 *
 * Stored in `Config.plugin_metadatas`. Each field corresponds to a registered
 * plugin and carries its typed metadata.
 *
 * Patch semantics: each plugin's meta is whole-replacement
 * (`Option<ExecutePluginMeta>` etc.), not a nested patch — the metas are
 * small (three fields) and have no Rust-side writer, so per-field patching
 * would only add eight patch structs for no race-safety. The TS side
 * expands its declarative partial into the full meta before sending (see
 * `expandPatch` in src/utils/patch.ts).
 */
export type PluginMetadatas = {
  execute: ExecutePluginMeta;
  autoUpload: AutoUploadPluginMeta;
  voiceSpeedup: VoiceSpeedupPluginMeta;
  voiceZerointerrupt: VoiceZerointerruptPluginMeta;
  gameWrapper: GameWrapperPluginMeta;
  localeEmulator: LocaleEmulatorPluginMeta;
  translator: TranslatorPluginMeta;
  wine: WinePluginMeta;
};
