// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteMetadata } from "./ExecuteMetadata";

export type PluginMetadata = { execute: ExecuteMetadata | null };
