// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecuteGameConfig } from "./ExecuteGameConfig";
import type { GameWrapperGameConfig } from "./GameWrapperGameConfig";
import type { LocaleEmulatorGameConfig } from "./LocaleEmulatorGameConfig";
import type { TranslatorGameConfig } from "./TranslatorGameConfig";
import type { VoiceSpeedupGameConfig } from "./VoiceSpeedupGameConfig";
import type { VoiceZerointerruptGameConfig } from "./VoiceZerointerruptGameConfig";

/**
 * A plugin instance attached to a game.
 *
 * This is a tagged union where the `pluginId` field discriminates the variant.
 * The same plugin can be attached multiple times to the same game, each with
 * its own config values.
 */
export type PluginInstance =
  | { "pluginId": "execute"; config: ExecuteGameConfig }
  | { "pluginId": "autoUpload" }
  | { "pluginId": "voiceSpeedup"; config: VoiceSpeedupGameConfig }
  | { "pluginId": "voiceZerointerrupt"; config: VoiceZerointerruptGameConfig }
  | { "pluginId": "gameWrapper"; config: GameWrapperGameConfig }
  | { "pluginId": "localeEmulator"; config: LocaleEmulatorGameConfig }
  | { "pluginId": "translator"; config: TranslatorGameConfig };
