// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoUploadPluginMeta } from "./AutoUploadPluginMeta";
import type { ExecutePluginMeta } from "./ExecutePluginMeta";
import type { GameWrapperPluginMeta } from "./GameWrapperPluginMeta";
import type { LocaleEmulatorPluginMeta } from "./LocaleEmulatorPluginMeta";
import type { TranslatorPluginMeta } from "./TranslatorPluginMeta";
import type { VoiceSpeedupPluginMeta } from "./VoiceSpeedupPluginMeta";
import type { VoiceZerointerruptPluginMeta } from "./VoiceZerointerruptPluginMeta";

/**
 * Per-plugin-type metadata, keyed by plugin ID.
 *
 * Stored in `Config.plugin_metadatas`. Each field corresponds to a registered
 * plugin and carries its typed metadata.
 */
export type PluginMetadatas = {
  execute: ExecutePluginMeta;
  autoUpload: AutoUploadPluginMeta;
  voiceSpeedup: VoiceSpeedupPluginMeta;
  voiceZerointerrupt: VoiceZerointerruptPluginMeta;
  gameWrapper: GameWrapperPluginMeta;
  localeEmulator: LocaleEmulatorPluginMeta;
  translator: TranslatorPluginMeta;
};
