// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoUploadPluginMeta } from "./AutoUploadPluginMeta";
import type { ExecutePluginMeta } from "./ExecutePluginMeta";
import type { GameWrapperPluginMeta } from "./GameWrapperPluginMeta";
import type { LocaleEmulatorPluginMeta } from "./LocaleEmulatorPluginMeta";
import type { TranslatorPluginMeta } from "./TranslatorPluginMeta";
import type { VoiceSpeedupPluginMeta } from "./VoiceSpeedupPluginMeta";
import type { VoiceZerointerruptPluginMeta } from "./VoiceZerointerruptPluginMeta";
import type { WinePluginMeta } from "./WinePluginMeta";

export type PluginMetadatasPatch = {
  execute?: ExecutePluginMeta;
  autoUpload?: AutoUploadPluginMeta;
  voiceSpeedup?: VoiceSpeedupPluginMeta;
  voiceZerointerrupt?: VoiceZerointerruptPluginMeta;
  gameWrapper?: GameWrapperPluginMeta;
  localeEmulator?: LocaleEmulatorPluginMeta;
  translator?: TranslatorPluginMeta;
  wine?: WinePluginMeta;
};
