// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoUploadPluginMetaPatch } from "./AutoUploadPluginMetaPatch";
import type { ExecutePluginMetaPatch } from "./ExecutePluginMetaPatch";
import type { GameWrapperPluginMetaPatch } from "./GameWrapperPluginMetaPatch";
import type { LocaleEmulatorPluginMetaPatch } from "./LocaleEmulatorPluginMetaPatch";
import type { TranslatorPluginMetaPatch } from "./TranslatorPluginMetaPatch";
import type { VoiceSpeedupPluginMetaPatch } from "./VoiceSpeedupPluginMetaPatch";
import type { VoiceZerointerruptPluginMetaPatch } from "./VoiceZerointerruptPluginMetaPatch";
import type { WinePluginMetaPatch } from "./WinePluginMetaPatch";

export type PluginMetadatasPatch = {
  execute: ExecutePluginMetaPatch;
  autoUpload: AutoUploadPluginMetaPatch;
  voiceSpeedup: VoiceSpeedupPluginMetaPatch;
  voiceZerointerrupt: VoiceZerointerruptPluginMetaPatch;
  gameWrapper: GameWrapperPluginMetaPatch;
  localeEmulator: LocaleEmulatorPluginMetaPatch;
  translator: TranslatorPluginMetaPatch;
  wine: WinePluginMetaPatch;
};
