// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the retention (末位淘汰) policy is enforced.
 */
export type RetentionScope = "local" | "remote" | "both";
