// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceConfigPatch } from "./AppearanceConfigPatch";
import type { ArchiveConfigPatch } from "./ArchiveConfigPatch";
import type { LaunchConfigPatch } from "./LaunchConfigPatch";
import type { StorageConfigPatch } from "./StorageConfigPatch";

export type SettingsPatch = {
  storage: StorageConfigPatch;
  archive: ArchiveConfigPatch;
  appearance: AppearanceConfigPatch;
  launch: LaunchConfigPatch;
  autoSyncInterval?: number;
  syncIoTimeoutSecs?: number;
  syncNonIoTimeoutSecs?: number;
};
