// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceConfig } from "./AppearanceConfig";
import type { ArchiveConfig } from "./ArchiveConfig";
import type { DeviceIdentity } from "./DeviceIdentity";
import type { StorageConfig } from "./StorageConfig";

export type Settings = {
  storage: StorageConfig;
  archive: ArchiveConfig;
  appearance: AppearanceConfig;
  currentDevice: DeviceIdentity;
};
