// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One import candidate from the local Steam library.
 */
export type SteamGameEntry = {
  appid: number;
  name: string;
  /**
   * Absolute install path, forward slashes (frontend convention).
   */
  installDir: string;
  sizeOnDisk: bigint | null;
  /**
   * CDN portrait cover straight into `Game::image_url` (no key, no quota);
   * downloaded by the existing `prepare_image` pipeline.
   */
  coverUrl: string;
  exePath: string | null;
};
