// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SteamGameEntry } from "./SteamGameEntry";

/**
 * Result of the import scan. A non-running Steam client is a state the UI
 * renders explicitly, not an IPC error.
 */
export type SteamListResult = { "type": "notRunning" } | {
  "type": "games";
  games: Array<SteamGameEntry>;
};
