// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Steam-specific metadata attached to an imported game (`Game::steam`).
 *
 * `appid` is the only authoritative identity — the install dir is
 * re-resolved from the live Steam library at every launch (so a relocated
 * library still works); the stored paths are per-device variable-templated
 * snapshots used as fallback.
 */
export type SteamInfo = {
  appid: number;
  /**
   * Absolute path of `steamapps/common/<installdir>`, variable-templated.
   */
  installDir: string;
  /**
   * Heuristic entry-exe guess made at import time; serves as the deploy
   * target for speedup-style DLL side-loading (`current_dir` derives from
   * it too). `None` when nothing plausible was found under the install dir.
   */
  exePath: string | null;
};
