// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { S3Config } from "./S3Config";
import type { WebDavConfig } from "./WebDavConfig";

export type StorageBackend = { "type": "webDav"; "config": WebDavConfig } | {
  "type": "s3";
  "config": S3Config;
} | { "type": "local"; "config": string };
