// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocalConfigPatch } from "./LocalConfigPatch";
import type { S3ConfigPatch } from "./S3ConfigPatch";
import type { StorageProvider } from "./StorageProvider";
import type { WebDavConfigPatch } from "./WebDavConfigPatch";

export type StorageConfigPatch = {
  provider?: StorageProvider;
  local: LocalConfigPatch;
  webdav: WebDavConfigPatch;
  s3: S3ConfigPatch;
};
