// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { S3Config } from "./S3Config";
import type { StorageProvider } from "./StorageProvider";
import type { WebDavConfig } from "./WebDavConfig";

export type StorageConfig = {
  provider: StorageProvider;
  local: string;
  webdav: WebDavConfig;
  s3: S3Config;
};
