// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload of the `sync://failed` event, emitted on each failed attempt of a
 * retried remote sync operation.
 */
export type SyncFailedPayload = {
  /**
   * Game whose sync operation hit the error; `None` for global operations
   * (e.g. config sync) that are not tied to a specific game.
   */
  gameId: number | null;
  /**
   * Human-readable error description.
   */
  message: string;
};
