// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which language the home-page "last played" timestamp should render
 * in, independent of the global UI language.
 */
export type TimeLanguage = "auto" | "en" | "zh";
