// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeFormat } from "./TimeFormat";
import type { TimeLanguage } from "./TimeLanguage";

export type TimeDisplayConfigPatch = {
  language?: TimeLanguage;
  format?: TimeFormat;
  absoluteFormat?: string;
};
