// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeFormat } from "./TimeFormat";
import type { TimeLanguage } from "./TimeLanguage";

export type TimeDisplayConfig = {
  language: TimeLanguage;
  format: TimeFormat;
  /**
   * Token-based format used when `format == Absolute`.
   *
   * Supported tokens (moment/dayjs-style):
   * `YYYY` `YY` `MM` `DD` `HH` `mm` `ss`.
   * Default: `"YYYY-MM-DD HH:mm"`.
   */
  absoluteFormat: string;
};
