// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Display style for the home-page "last played" timestamp.
 */
export type TimeFormat = "relative" | "absolute";
