// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranslatorGameConfig } from "./TranslatorGameConfig";

export type TranslatorPluginMetaPatch = {
  enabled?: boolean;
  autoAdd?: boolean;
  configDefaults?: TranslatorGameConfig;
};
