// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranslatorGameConfig } from "./TranslatorGameConfig";

/**
 * Global metadata for the Translator plugin (stored in `PluginMetadatas`).
 */
export type TranslatorPluginMeta = {
  enabled: boolean;
  autoAdd: boolean;
  configDefaults: TranslatorGameConfig;
};
