// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExitSignal } from "./ExitSignal";

/**
 * Per-game config for the Translator plugin.
 */
export type TranslatorGameConfig = {
  /**
   * The command to launch the translator tool.
   */
  cmd: string;
  /**
   * Working directory. If empty, defaults to the directory of the program
   * (first argument of cmd).
   */
  currentDir: string;
  /**
   * Signal to send to the translator process when the game exits.
   * Defaults to SIGTERM (graceful shutdown).
   */
  exitSignal: ExitSignal;
};
