// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchPreference } from "./ArchPreference";

/**
 * Per-game config for the VoiceZerointerrupt plugin.
 */
export type VoiceZerointerruptGameConfig = {
  /**
   * Architecture preference for DLL selection.
   */
  arch: ArchPreference;
};
