// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceSpeedupGameConfig } from "./VoiceSpeedupGameConfig";

export type VoiceSpeedupPluginMetaPatch = {
  enabled?: boolean;
  autoAdd?: boolean;
  configDefaults?: VoiceSpeedupGameConfig;
};
