// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArchPreference } from "./ArchPreference";
import type { SpeedupProvider } from "./SpeedupProvider";

/**
 * Per-game config for the VoiceSpeedup plugin.
 */
export type VoiceSpeedupGameConfig = {
  /**
   * Playback speed multiplier (1.0 ~ 2.0).
   */
  speed: number;
  /**
   * DLL injection provider.
   */
  provider: SpeedupProvider;
  /**
   * Architecture preference for DLL selection.
   */
  arch: ArchPreference;
};
