// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceZerointerruptGameConfig } from "./VoiceZerointerruptGameConfig";

/**
 * Global metadata for the VoiceZerointerrupt plugin (stored in
 * `PluginMetadatas`).
 */
export type VoiceZerointerruptPluginMeta = {
  enabled: boolean;
  autoAdd: boolean;
  configDefaults: VoiceZerointerruptGameConfig;
};
