// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceZerointerruptGameConfig } from "./VoiceZerointerruptGameConfig";

export type VoiceZerointerruptPluginMetaPatch = {
  enabled?: boolean;
  autoAdd?: boolean;
  configDefaults?: VoiceZerointerruptGameConfig;
};
