// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VoiceSpeedupGameConfig } from "./VoiceSpeedupGameConfig";

/**
 * Global metadata for the VoiceSpeedup plugin (stored in `PluginMetadatas`).
 */
export type VoiceSpeedupPluginMeta = {
  enabled: boolean;
  autoAdd: boolean;
  configDefaults: VoiceSpeedupGameConfig;
};
