// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DllOverride } from "./DllOverride";
import type { WineArch } from "./WineArch";

/**
 * Per-game config for the Wine plugin.
 */
export type WineGameConfig = {
  /**
   * `WINEPREFIX` path. Supports `~` and `{variables}`. Empty falls back
   * to Wine's default (`~/.wine`).
   */
  prefix: string;
  /**
   * `WINEARCH` value.
   */
  arch: WineArch;
  /**
   * Sets `WINEESYNC=1` when true.
   */
  esync: boolean;
  /**
   * Sets `WINEFSYNC=1` when true.
   */
  fsync: boolean;
  /**
   * Entries for the `WINEDLLOVERRIDES` env var.
   */
  dllOverrides: { [key in string]: DllOverride };
  /**
   * `LC_ALL` override, e.g. `"ja_JP.UTF-8"`. Empty = no override.
   */
  locale: string;
  /**
   * Run `wineserver -k` after the game exits to tear down the prefix.
   */
  killWineserverOnExit: boolean;
  /**
   * Additional env vars, applied on top of the Wine-derived ones.
   */
  extraEnv: { [key in string]: string };
};
