// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wine architecture preference, mapped to the `WINEARCH` env var.
 */
export type WineArch = "win64" | "win32";
