// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WineGameConfig } from "./WineGameConfig";

/**
 * Global metadata for the Wine plugin (stored in `PluginMetadatas`).
 */
export type WinePluginMeta = {
  enabled: boolean;
  autoAdd: boolean;
  configDefaults: WineGameConfig;
};
