// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WineGameConfig } from "./WineGameConfig";

export type WinePluginMetaPatch = {
  enabled?: boolean;
  autoAdd?: boolean;
  configDefaults?: WineGameConfig;
};
