// Patch IPC types & helpers.
//
// `ConfigPatch` / `GamePatch` / `DevicePatch` / `ListPatchOp` are
// auto-generated by ts-rs (`@bindings/*`). What lives here:
//
//   1. `GameListOp` / `DeviceListOp` — the generated generic `ListPatchOp`
//      instantiated with the concrete element/patch/id types (and with the
//      DeepPartial patch type we actually put on the wire), so call sites
//      get a short name.
//
//   2. `diffGame` — compute a field-wise diff between two snapshots of one
//      game, for callers (the edit dialog) that replace a whole game object
//      but should only ship the changed fields. Only changed fields land in
//      the patch, which is exactly what stops the frontend from clobbering
//      fields the Rust game loop just wrote (use_time / daily_playtime /
//      last_played_time) with a stale snapshot.

import type { ConfigPatch as RustConfigPatch } from '@bindings/ConfigPatch'
import type { Device } from '@bindings/Device'
import type { DevicePatch as RustDevicePatch } from '@bindings/DevicePatch'
import type { Game } from '@bindings/Game'
import type { GamePatch as RustGamePatch } from '@bindings/GamePatch'
import type { ListPatchOp } from '@bindings/ListPatchOp'
import { unwrap } from 'solid-js/store'

// `games`/`devices` are overridden with the DeepPartial-value op aliases
// above (the generated `ConfigPatch` references the non-DeepPartial
// `GamePatch`/`DevicePatch`).
export type ConfigPatch = Omit<DeepPartial<RustConfigPatch>, 'devices' | 'games'> & {
  devices?: DeviceListOp[]
  games?: GameListOp[]
}

/** Recursive `Partial` — like `Partial` but applied at every level of nesting.
 *
 * Why we need it: `#[patch(nesting)]` on the Rust side produces patch fields
 * that are *required* in Rust (and therefore in the ts-rs output), even
 * though they're wire-optional thanks to `#[serde(default)]`. This type
 * makes every field optional at every level so callers can write
 * `{ appearance: { theme: 'dark' } }` without filling in every leaf.
 *
 * Arrays are treated as leaves (we never want to partialize array elements —
 * a `GameListOp` is always sent whole, same for `plugins`, `savePaths`,
 * `variables`, …). */
export type DeepPartial<T> = T extends unknown[]
  ? T
  : T extends object
    ? { [P in keyof T]?: DeepPartial<T[P]> }
    : T
/** Same as `GameListOp` but for `Config.devices`, keyed by `Device.uid`. */
export type DeviceListOp = ListPatchOp<Device, DevicePatch, string>

export type DevicePatch = DeepPartial<RustDevicePatch>

/** Fine-grained operation on `Config.games`, addressed by `Game.id`.
 * Unknown ids in `modify` / `delete` are silently ignored by the backend,
 * so stale ops are safe. */
export type GameListOp = ListPatchOp<Game, GamePatch, number>

// Shadow the ts-rs-generated patch types with `DeepPartial<...>` versions.
// The Rust originals have several REQUIRED nested fields (a side-effect of
// `#[patch(nesting)]` and the list-patch `Vec` fields), but the wire format
// is genuinely partial — Rust's `#[serde(default)]` fills absent fields
// with empty sub-patches (all-None), which `apply` treats as a no-op.
export type GamePatch = DeepPartial<RustGamePatch>

// ── Single-op builders ────────────────────────────────────────────────────
//
// Thin helpers for callers that know exactly what they changed — they can
// build a `ConfigPatch` directly without diffing. This is the cheap path
// used by most store actions (addGame, removeGame, setImageHash, …).

/** Build a patch that appends a new device. */
export function appendDeviceOp(device: Device): ConfigPatch {
  return { devices: [{ op: 'append', value: device }] }
}

/** Build a patch that appends a new game. */
export function appendGameOp(game: Game): ConfigPatch {
  return { games: [{ op: 'append', value: game }] }
}

/** Recursively merge a patch into a target (the SolidJS produce draft).
 *
 * For each key in `patch`:
 *   - `undefined` → skip (means "no change")
 *   - plain object AND target[key] is a plain object → recurse
 *   - anything else (including arrays and `null`) → assign directly
 *
 * the runtime check (`isPlainObject`) is the source of truth, so `unknown`
 * is safe — only the one recursive call site needs a cast. */
export function applyPatch(
  target: Record<string, unknown>,
  patch: Record<string, unknown>
): void {
  if (!isPlainObject(target) || !isPlainObject(patch)) return
  for (const key in patch) {
    const value = patch[key]
    if (value === undefined) continue
    if (isPlainObject(value) && isPlainObject(target[key])) {
      applyPatch(target[key], value)
    } else {
      target[key] = value
    }
  }
}

/** Build a patch that deletes a device by uid. */
export function deleteDeviceOp(id: string): ConfigPatch {
  return { devices: [{ id, op: 'delete' }] }
}

/** Build a patch that deletes a game by id. */
export function deleteGameOp(id: number): ConfigPatch {
  return { games: [{ id, op: 'delete' }] }
}

/** Compute a field-wise diff of two `Game` objects (same id). Only changed
 * fields land in the returned patch; an unchanged game yields `{}`.
 *
 * Exported so callers that "replace" a whole game (e.g. the game edit
 * dialog) can still send an incremental patch — `replaceGame` knows which
 * id it's editing, just not which fields changed. */
export function diffGame(base: Game, current: Game): GamePatch {
  const p: Record<string, unknown> = {}
  if (base.name !== current.name) p.name = current.name
  if (!jsonEq(base.excutablePath, current.excutablePath))
    p.excutablePath = current.excutablePath
  if (!jsonEq(base.savePaths, current.savePaths)) p.savePaths = current.savePaths
  if (!jsonEq(base.imageUrl, current.imageUrl)) p.imageUrl = current.imageUrl
  if (!jsonEq(base.imageSha256, current.imageSha256)) p.imageSha256 = current.imageSha256
  if (base.addedTime !== current.addedTime) p.addedTime = current.addedTime
  if (!jsonEq(base.useTime, current.useTime)) p.useTime = current.useTime
  if (!jsonEq(base.lastPlayedTime, current.lastPlayedTime))
    p.lastPlayedTime = current.lastPlayedTime
  if (!jsonEq(base.lastUploadTime, current.lastUploadTime))
    p.lastUploadTime = current.lastUploadTime
  if (!jsonEq(base.dailyPlaytime, current.dailyPlaytime))
    p.dailyPlaytime = current.dailyPlaytime
  if (!jsonEq(base.coverColor, current.coverColor)) p.coverColor = current.coverColor
  if (!jsonEq(base.plugins, current.plugins)) p.plugins = current.plugins
  return p
}

/** Expand a declarative deep-partial patch (e.g. `{ storage: { webdav:
 *  { username } } }`) into the whole-sub-object form the backend expects.
 *
 * Small, race-free sub-structs (`settings.storage`, `settings.appearance`,
 * each plugin's meta, …) are whole-replacement on the Rust side
 * (`Option<T>` patch fields), so the wire value must be the *complete*
 * sub-struct, not a partial. For each top-level key: a plain-object value
 * is deep-merged onto the current store value (yielding the full
 * sub-struct); scalars pass through unchanged.
 *
 * `base` may be a SolidJS store proxy — it is unwrapped and cloned before
 * merging, so the store itself is never mutated here. */
export function expandPatch<T extends Record<string, unknown>>(
  base: T,
  patch: DeepPartial<T>
): { [K in keyof T]?: T[K] } {
  const out: Record<string, unknown> = {}
  for (const key in patch) {
    const v = (patch as Record<string, unknown>)[key]
    if (v === undefined) continue
    if (isPlainObject(v) && isPlainObject(base[key])) {
      const merged = structuredClone(unwrap(base[key]))
      applyPatch(merged, v)
      out[key] = merged
    } else {
      out[key] = v
    }
  }
  return out as { [K in keyof T]?: T[K] }
}

/** Merge two patches into one. `games`/`devices` ops are concatenated (the
 * backend applies them in order, so coalescing same-id modifies is
 * unnecessary); `settings`/`pluginMetadatas` are **deep**-merged (a shallow
 * `{...a, ...b}` would silently drop sibling edits made within the same
 * debounce window — e.g. webdav `endpoint` then `username`, both nested
 * under `settings.storage.webdav` — diverging the store, which applied
 * both, from the backend, which would receive only the latest). Every
 * other field takes the right-hand (latest) value. Used by the debounced
 * patch path to coalesce rapid mutations into one IPC. */
export function mergeConfigPatches(a: ConfigPatch, b: ConfigPatch): ConfigPatch {
  const merged: ConfigPatch = { ...a, ...b }
  if (a.games || b.games) {
    merged.games = [...(a.games ?? []), ...(b.games ?? [])]
  }
  if (a.devices || b.devices) {
    merged.devices = [...(a.devices ?? []), ...(b.devices ?? [])]
  }
  if (isPlainObject(a.settings) && isPlainObject(b.settings)) {
    const s = structuredClone(a.settings)
    applyPatch(s, b.settings)
    merged.settings = s
  }
  if (isPlainObject(a.pluginMetadatas) && isPlainObject(b.pluginMetadatas)) {
    const p = structuredClone(a.pluginMetadatas)
    applyPatch(p, b.pluginMetadatas)
    merged.pluginMetadatas = p
  }
  return merged
}

// ── applyPatch: deep-merge a patch into a draft ─────────────────────────────
//
// Used by declarative store actions (e.g. `updateSettings(patch)`) to mirror
// the Rust-side `apply` on the local SolidJS store, so the UI updates before
// the IPC roundtrip completes. Recurses through plain objects only — arrays
// and primitive fields are replaced whole, matching struct-patch's semantics
// for the leaf patch fields (Option<T>) and the whole-replacement fields
// (`save_paths`, `variables`, etc.).

/** Build a patch that upserts a device (modify by uid). */
export function modifyDeviceOp(id: string, patch: DevicePatch): ConfigPatch {
  return { devices: [{ id, op: 'modify', value: patch }] }
}

/** Build a patch that applies a sub-patch to one game by id. */
export function modifyGameOp(id: number, patch: GamePatch): ConfigPatch {
  return { games: [{ id, op: 'modify', value: patch }] }
}

/** Refresh backend-owned fields on an edit dialog's submit snapshot.
 *
 * The dialog edits a deep clone taken when it opened. While it is open, the
 * Rust game loop / archive upload may write `useTime`, `dailyPlaytime`,
 * `lastPlayedTime` and `lastUploadTime` — diffing the stale clone against
 * the live store (what `replaceGame` does) would ship those fields as
 * "changes" and revert the backend writes (e.g. losing a play session that
 * ended mid-edit). The two form-editable fields (`useTime`,
 * `lastPlayedTime`) are only taken from `live` when the user left them
 * untouched (still equal to the open-time `snapshot`); `dailyPlaytime` /
 * `lastUploadTime` are not editable anywhere and always come from `live`.
 * Returns a clone; inputs are not modified. */
export function refreshBackendOwnedFields(
  snapshot: Game,
  edited: Game,
  live: Game
): Game {
  const rawEdited = unwrap(edited)
  const rawLive = unwrap(live)
  const out = structuredClone(rawEdited)
  if (jsonEq(rawEdited.useTime, snapshot.useTime)) out.useTime = rawLive.useTime
  if (jsonEq(rawEdited.lastPlayedTime, snapshot.lastPlayedTime))
    out.lastPlayedTime = rawLive.lastPlayedTime
  out.dailyPlaytime = rawLive.dailyPlaytime
  out.lastUploadTime = rawLive.lastUploadTime
  return out
}

// ── Diff helpers ───────────────────────────────────────────────────────────

/** True for plain JS objects (not arrays, not null, not class instances). */
function isPlainObject(v: unknown): v is Record<string, unknown> {
  return (
    typeof v === 'object' &&
    v !== null &&
    !Array.isArray(v) &&
    (Object.getPrototypeOf(v) === Object.prototype || Object.getPrototypeOf(v) === null)
  )
}

/** Cheap structural equality via JSON. Adequate for our config shapes
 * (everything is JSON-serializable) and avoids pulling in a deep-equal
 * dependency. Called on already-changed subtrees, so the cost is bounded. */
function jsonEq<T>(a: T, b: T): boolean {
  return JSON.stringify(a) === JSON.stringify(b)
}
