// Patch IPC types & helpers.
//
// `ConfigPatch` / `GamePatch` themselves are auto-generated by ts-rs
// (`@bindings/ConfigPatch`, `@bindings/GamePatch`). What lives here:
//
//   1. `GameListOp` — the concrete shape of `ListPatchOp<Game, GamePatch,
//      number>` from struct-patch. The Rust macro generates a generic enum
//      that doesn't derive `ts_rs::TS`, so on the Rust side we override the
//      TS type via `#[ts(type = "Array<GameListOp>")]`. ts-rs then emits the
//      field as `Array<GameListOp>` without emitting an import, which is why
//      we publish `GameListOp` from this module and re-export a corrected
//      `ConfigPatch` that wires the import up.
//
//   2. `diffGame` — compute a field-wise diff between two snapshots of one
//      game, for callers (the edit dialog) that replace a whole game object
//      but should only ship the changed fields. Only changed fields land in
//      the patch, which is exactly what stops the frontend from clobbering
//      fields the Rust game loop just wrote (use_time / daily_playtime /
//      last_played_time) with a stale snapshot.
//
// Rust serialization of the op enum uses snake_case tags
// (`{"op":"modify","id":1,"value":{...}}`) — see `struct-patch`'s
// `lib/src/list.rs`. Keep these variants in sync with that file.

import type { ConfigPatch as RustConfigPatch } from '@bindings/ConfigPatch'
import type { Device } from '@bindings/Device'
import type { DevicePatch as RustDevicePatch } from '@bindings/DevicePatch'
import type { Game } from '@bindings/Game'
import type { GamePatch as RustGamePatch } from '@bindings/GamePatch'

/** Recursive `Partial` — like `Partial` but applied at every level of nesting.
 *
 * Why we need it: `#[patch(nesting)]` on the Rust side produces patch fields
 * that are *required* in Rust (and therefore in the ts-rs output), even
 * though they're wire-optional thanks to `#[serde(default)]`. This type
 * makes every field optional at every level so callers can write
 * `{ appearance: { theme: 'dark' } }` without filling in every leaf.
 *
 * Arrays are treated as leaves (we never want to partialize array elements —
 * a `GameListOp` is always sent whole, same for `plugins`, `savePaths`,
 * `variables`, …). */
export type DeepPartial<T> = T extends Array<unknown>
  ? T
  : T extends object
    ? { [P in keyof T]?: DeepPartial<T[P]> }
    : T

/** Fine-grained operation on `Config.games`, addressed by `Game.id`.
 *
 * Mirrors `struct_patch::list::ListPatchOp<Game, GamePatch, u32>` on the
 * Rust side. Unknown ids in `modify` / `delete` are silently ignored when
 * applied, so stale ops are safe. */
export type GameListOp =
  | { op: 'prepend'; value: Game }
  | { op: 'append'; value: Game }
  | { op: 'insert'; index: number; value: Game }
  | { op: 'modify'; id: number; value: GamePatch }
  | { op: 'delete'; id: number }

/** Same shape as `GameListOp` but for `Config.devices`, keyed by `uid`.
 * Mirrors `ListPatchOp<Device, DevicePatch, String>`. */
export type DeviceListOp =
  | { op: 'prepend'; value: Device }
  | { op: 'append'; value: Device }
  | { op: 'insert'; index: number; value: Device }
  | { op: 'modify'; id: string; value: DevicePatch }
  | { op: 'delete'; id: string }

// Shadow the ts-rs-generated patch types with `DeepPartial<...>` versions.
// The Rust originals have several REQUIRED nested fields (a side-effect of
// `#[patch(nesting)]`), but the wire format is genuinely partial — Rust's
// `#[serde(default)]` fills absent fields with empty sub-patches (all-None),
// which `apply` treats as a no-op.
export type ConfigPatch = DeepPartial<RustConfigPatch>
export type GamePatch = DeepPartial<RustGamePatch>
export type DevicePatch = DeepPartial<RustDevicePatch>

// ── Single-op builders ────────────────────────────────────────────────────
//
// Thin helpers for callers that know exactly what they changed — they can
// build a `ConfigPatch` directly without diffing. This is the cheap path
// used by most store actions (addGame, removeGame, setImageHash, …).

/** Build a patch that appends a new game. */
export function appendGameOp(game: Game): ConfigPatch {
  return { games: [{ op: 'append', value: game }] }
}

/** Build a patch that deletes a game by id. */
export function deleteGameOp(id: number): ConfigPatch {
  return { games: [{ op: 'delete', id }] }
}

/** Build a patch that deletes a device by uid. */
export function deleteDeviceOp(id: string): ConfigPatch {
  return { devices: [{ op: 'delete', id }] }
}

/** Build a patch that applies a sub-patch to one game by id. */
export function modifyGameOp(id: number, patch: GamePatch): ConfigPatch {
  return { games: [{ op: 'modify', id, value: patch }] }
}

/** Build a patch that upserts a device (modify by uid). */
export function modifyDeviceOp(id: string, patch: DevicePatch): ConfigPatch {
  return { devices: [{ op: 'modify', id, value: patch }] }
}

/** Build a patch that appends a new device. */
export function appendDeviceOp(device: Device): ConfigPatch {
  return { devices: [{ op: 'append', value: device }] }
}

/** Merge two patches into one. `games`/`devices` ops are concatenated (the
 * backend applies them in order, so coalescing same-id modifies is
 * unnecessary); `settings`/`pluginMetadatas` are **deep**-merged (a shallow
 * `{...a, ...b}` would silently drop sibling edits made within the same
 * debounce window — e.g. webdav `endpoint` then `username`, both nested
 * under `settings.storage.webdav` — diverging the store, which applied
 * both, from the backend, which would receive only the latest). Every
 * other field takes the right-hand (latest) value. Used by the debounced
 * patch path to coalesce rapid mutations into one IPC. */
export function mergeConfigPatches(a: ConfigPatch, b: ConfigPatch): ConfigPatch {
  const merged: ConfigPatch = { ...a, ...b }
  if (a.games || b.games) {
    merged.games = [...(a.games ?? []), ...(b.games ?? [])]
  }
  if (a.devices || b.devices) {
    merged.devices = [...(a.devices ?? []), ...(b.devices ?? [])]
  }
  if (isPlainObject(a.settings) && isPlainObject(b.settings)) {
    const s = structuredClone(a.settings)
    applyPatch(s, b.settings)
    merged.settings = s as ConfigPatch['settings']
  }
  if (isPlainObject(a.pluginMetadatas) && isPlainObject(b.pluginMetadatas)) {
    const p = structuredClone(a.pluginMetadatas)
    applyPatch(p, b.pluginMetadatas)
    merged.pluginMetadatas = p as ConfigPatch['pluginMetadatas']
  }
  return merged
}

// ── applyPatch: deep-merge a patch into a draft ─────────────────────────────
//
// Used by declarative store actions (e.g. `updateSettings(patch)`) to mirror
// the Rust-side `apply` on the local SolidJS store, so the UI updates before
// the IPC roundtrip completes. Recurses through plain objects only — arrays
// and primitive fields are replaced whole, matching struct-patch's semantics
// for the leaf patch fields (Option<T>) and the whole-replacement fields
// (`save_paths`, `variables`, etc.).

/** True for plain JS objects (not arrays, not null, not class instances). */
function isPlainObject(v: unknown): v is Record<string, unknown> {
  return (
    typeof v === 'object' &&
    v !== null &&
    !Array.isArray(v) &&
    (Object.getPrototypeOf(v) === Object.prototype ||
      Object.getPrototypeOf(v) === null)
  )
}

/** Recursively merge a patch into a target (the SolidJS produce draft).
 *
 * For each key in `patch`:
 *   - `undefined` → skip (means "no change")
 *   - plain object AND target[key] is a plain object → recurse
 *   - anything else (including arrays and `null`) → assign directly
 *
 * Spelled with `Record<string, unknown>` rather than generics so the
 * recursive call doesn't need a cast at every level — the runtime check
 * (`isPlainObject`) is the source of truth, the types just have to be
 * permissive enough to follow. */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function applyPatch(target: Record<string, any>, patch: Record<string, any>): void {
  if (!isPlainObject(target) || !isPlainObject(patch)) return
  for (const key in patch) {
    const val = patch[key]
    if (val === undefined) continue
    if (isPlainObject(val) && isPlainObject(target[key])) {
      applyPatch(target[key], val)
    } else {
      target[key] = val
    }
  }
}

// ── Diff helpers ───────────────────────────────────────────────────────────

/** Cheap structural equality via JSON. Adequate for our config shapes
 * (everything is JSON-serializable) and avoids pulling in a deep-equal
 * dependency. Called on already-changed subtrees, so the cost is bounded. */
function jsonEq<T>(a: T, b: T): boolean {
  return JSON.stringify(a) === JSON.stringify(b)
}

/** Compute a field-wise diff of two `Game` objects (same id). Only changed
 * fields land in the returned patch; an unchanged game yields `{}`.
 *
 * Exported so callers that "replace" a whole game (e.g. the game edit
 * dialog) can still send an incremental patch — `replaceGame` knows which
 * id it's editing, just not which fields changed. */
export function diffGame(base: Game, cur: Game): GamePatch {
  const p: Record<string, unknown> = {}
  if (base.name !== cur.name) p.name = cur.name
  if (!jsonEq(base.excutablePath, cur.excutablePath))
    p.excutablePath = cur.excutablePath
  if (!jsonEq(base.savePaths, cur.savePaths)) p.savePaths = cur.savePaths
  if (!jsonEq(base.imageUrl, cur.imageUrl)) p.imageUrl = cur.imageUrl
  if (!jsonEq(base.imageSha256, cur.imageSha256)) p.imageSha256 = cur.imageSha256
  if (base.addedTime !== cur.addedTime) p.addedTime = cur.addedTime
  if (!jsonEq(base.useTime, cur.useTime)) p.useTime = cur.useTime
  if (!jsonEq(base.lastPlayedTime, cur.lastPlayedTime))
    p.lastPlayedTime = cur.lastPlayedTime
  if (!jsonEq(base.lastUploadTime, cur.lastUploadTime))
    p.lastUploadTime = cur.lastUploadTime
  if (!jsonEq(base.dailyPlaytime, cur.dailyPlaytime))
    p.dailyPlaytime = cur.dailyPlaytime
  if (!jsonEq(base.coverColor, cur.coverColor)) p.coverColor = cur.coverColor
  if (!jsonEq(base.plugins, cur.plugins)) p.plugins = cur.plugins
  return p as GamePatch
}
