name: Update Node Dependencies
on:
  push:
    branches:
      - 'renovate/**'
    paths:
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build frontend application
        run: pnpm run build
